//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtariGo.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtariGo.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmAction_Btn_Cancel {
            get {
                return ResourceManager.GetString("ConfirmAction_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmAction_Btn_Confirm {
            get {
                return ResourceManager.GetString("ConfirmAction_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ForgotPassword_Btn_Accept {
            get {
                return ResourceManager.GetString("ForgotPassword_Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ForgotPassword_Btn_Cancel {
            get {
                return ResourceManager.GetString("ForgotPassword_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username cannot be empty..
        /// </summary>
        public static string ForgotPassword_Err_Empty {
            get {
                return ResourceManager.GetString("ForgotPassword_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Username.
        /// </summary>
        public static string ForgotPassword_Lbl_EmailOrUsername {
            get {
                return ResourceManager.GetString("ForgotPassword_Lbl_EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Password.
        /// </summary>
        public static string ForgotPassword_Lbl_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ForgotVerification_Btn_Cancel {
            get {
                return ResourceManager.GetString("ForgotVerification_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ForgotVerification_Btn_Confirm {
            get {
                return ResourceManager.GetString("ForgotVerification_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code cannot be empty..
        /// </summary>
        public static string ForgotVerification_Err_EmptyCode {
            get {
                return ResourceManager.GetString("ForgotVerification_Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a 6-digit code to your email to change your password..
        /// </summary>
        public static string ForgotVerification_Lbl_Description {
            get {
                return ResourceManager.GetString("ForgotVerification_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        public static string ForgotVerification_Lbl_Title {
            get {
                return ResourceManager.GetString("ForgotVerification_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string GameBoard_Btn_Report {
            get {
                return ResourceManager.GetString("GameBoard_Btn_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        public static string GameBoard_Btn_Surrender {
            get {
                return ResourceManager.GetString("GameBoard_Btn_Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match has started..
        /// </summary>
        public static string GameBoard_Chat_GameStarted {
            get {
                return ResourceManager.GetString("GameBoard_Chat_GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck!.
        /// </summary>
        public static string GameBoard_Chat_GoodLuck {
            get {
                return ResourceManager.GetString("GameBoard_Chat_GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string GameBoard_Lbl_Black {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat is not available for guests..
        /// </summary>
        public static string GameBoard_Lbl_ChatDisabledGuest {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_ChatDisabledGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Chat.
        /// </summary>
        public static string GameBoard_Lbl_ChatTitle {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string GameBoard_Lbl_Opponent {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string GameBoard_Lbl_System {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string GameBoard_Lbl_White {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU.
        /// </summary>
        public static string GameBoard_Lbl_You {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent&apos;s turn! Waiting for move....
        /// </summary>
        public static string GameBoard_Status_OpponentTurn {
            get {
                return ResourceManager.GetString("GameBoard_Status_OpponentTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn! Click on an intersection.
        /// </summary>
        public static string GameBoard_Status_YourTurn {
            get {
                return ResourceManager.GetString("GameBoard_Status_YourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        public static string GameBoard_Surrender_Confirm {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to surrender this match?.
        /// </summary>
        public static string GameBoard_Surrender_Message {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender Match.
        /// </summary>
        public static string GameBoard_Surrender_Title {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message....
        /// </summary>
        public static string GameBoard_Txt_ChatPlaceholder {
            get {
                return ResourceManager.GetString("GameBoard_Txt_ChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Lang_Btn_Accept {
            get {
                return ResourceManager.GetString("Lang_Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Lang_Btn_Cancel {
            get {
                return ResourceManager.GetString("Lang_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Lang_Modal_Title {
            get {
                return ResourceManager.GetString("Lang_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SearchingOpponent_Btn_Cancel {
            get {
                return ResourceManager.GetString("SearchingOpponent_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate match found.
        /// </summary>
        public static string SearchingOpponent_Btn_SimulateMatch {
            get {
                return ResourceManager.GetString("SearchingOpponent_Btn_SimulateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchingOpponent_Lbl_Searching {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCHING FOR OPPONENT.
        /// </summary>
        public static string SearchingOpponent_Lbl_SearchingOpponent {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_SearchingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string SearchingOpponent_Lbl_You {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Login_Btn_Exit {
            get {
                return ResourceManager.GetString("Login_Btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as Guest.
        /// </summary>
        public static string Login_Btn_Guest {
            get {
                return ResourceManager.GetString("Login_Btn_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Login_Btn_LanguageLabel {
            get {
                return ResourceManager.GetString("Login_Btn_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login_Btn_Submit {
            get {
                return ResourceManager.GetString("Login_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Lbl_Email {
            get {
                return ResourceManager.GetString("Login_Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Lbl_Password {
            get {
                return ResourceManager.GetString("Login_Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Lbl_Title {
            get {
                return ResourceManager.GetString("Login_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Login_Lnk_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_Lnk_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign up.
        /// </summary>
        public static string Login_Lnk_Register {
            get {
                return ResourceManager.GetString("Login_Lnk_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string Login_Tip_ChangeLanguage {
            get {
                return ResourceManager.GetString("Login_Tip_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user@mail.com.
        /// </summary>
        public static string Login_Txt_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_Txt_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........
        /// </summary>
        public static string Login_Txt_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_Txt_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add new friend.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_AddFriend {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Private Room.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_CreatePrivateRoom {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_CreatePrivateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Customize {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ?.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Email {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Invite {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join with Code.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_JoinWithCode {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_JoinWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Options {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Multiplayer.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_PlayMultiplayer {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_PlayMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_SignOut {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?? Friends List.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_FriendsList {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_FriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?? Global Top.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_TopGlobal {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_TopGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins: .
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_Victories {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN LOBBY - Welcome .
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_Welcome {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you
        ///      like to do?.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_WhatToDo {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_WinsHeader {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_WinsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_YourProfile {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_YourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search friend....
        /// </summary>
        public static string RegisterPlayerLobby_Txt_SearchFriendPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Txt_SearchFriendPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewPassword_Btn_Cancel {
            get {
                return ResourceManager.GetString("NewPassword_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Change.
        /// </summary>
        public static string NewPassword_Btn_ConfirmChange {
            get {
                return ResourceManager.GetString("NewPassword_Btn_ConfirmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords cannot be empty..
        /// </summary>
        public static string NewPassword_Err_Empty {
            get {
                return ResourceManager.GetString("NewPassword_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string NewPassword_Err_Mismatch {
            get {
                return ResourceManager.GetString("NewPassword_Err_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string NewPassword_Lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword_Lbl_NewPassword {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string NewPassword_Lbl_Title {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string Options_Btn_SaveAndClose {
            get {
                return ResourceManager.GetString("Options_Btn_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atari Go Multiplayer v1.0.
        /// </summary>
        public static string Options_Lbl_AppVersion {
            get {
                return ResourceManager.GetString("Options_Lbl_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Music.
        /// </summary>
        public static string Options_Lbl_BackgroundMusic {
            get {
                return ResourceManager.GetString("Options_Lbl_BackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Options_Lbl_Language {
            get {
                return ResourceManager.GetString("Options_Lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effects.
        /// </summary>
        public static string Options_Lbl_SoundEffects {
            get {
                return ResourceManager.GetString("Options_Lbl_SoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Lbl_Title {
            get {
                return ResourceManager.GetString("Options_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Register_Btn_Back {
            get {
                return ResourceManager.GetString("Register_Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Register_Btn_Register {
            get {
                return ResourceManager.GetString("Register_Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and email cannot be empty..
        /// </summary>
        public static string Register_Err_EmptyFields {
            get {
                return ResourceManager.GetString("Register_Err_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Lbl_Email {
            get {
                return ResourceManager.GetString("Register_Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Min. 8 chars, 1 Uppercase).
        /// </summary>
        public static string Register_Lbl_Password {
            get {
                return ResourceManager.GetString("Register_Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        public static string Register_Lbl_Title {
            get {
                return ResourceManager.GetString("Register_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Register_Lbl_Username {
            get {
                return ResourceManager.GetString("Register_Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ReportPlayer_Btn_Cancel {
            get {
                return ResourceManager.GetString("ReportPlayer_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Report.
        /// </summary>
        public static string ReportPlayer_Btn_Submit {
            get {
                return ResourceManager.GetString("ReportPlayer_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Details (Optional).
        /// </summary>
        public static string ReportPlayer_Lbl_Details {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: .
        /// </summary>
        public static string ReportPlayer_Lbl_PlayerFormat {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_PlayerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infraction Reason.
        /// </summary>
        public static string ReportPlayer_Lbl_Reason {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Player.
        /// </summary>
        public static string ReportPlayer_Lbl_Title {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheating or Hacking.
        /// </summary>
        public static string ReportPlayer_Reason_Cheating {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Cheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive Language.
        /// </summary>
        public static string ReportPlayer_Reason_OffensiveLanguage {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_OffensiveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ReportPlayer_Reason_Other {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsportsmanlike Conduct.
        /// </summary>
        public static string ReportPlayer_Reason_Unsportsmanlike {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Unsportsmanlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Verification_Btn_Cancel {
            get {
                return ResourceManager.GetString("Verification_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and Enter.
        /// </summary>
        public static string Verification_Btn_Confirm {
            get {
                return ResourceManager.GetString("Verification_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code cannot be empty..
        /// </summary>
        public static string Verification_Err_EmptyCode {
            get {
                return ResourceManager.GetString("Verification_Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a 6-digit code to your email to verify your account..
        /// </summary>
        public static string Verification_Lbl_Description {
            get {
                return ResourceManager.GetString("Verification_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        public static string Verification_Lbl_Title {
            get {
                return ResourceManager.GetString("Verification_Lbl_Title", resourceCulture);
            }
        }
    }
}
