//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtariGo.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtariGo.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string ConfirmAction_Btn_Cancel {
            get {
                return ResourceManager.GetString("ConfirmAction_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string ConfirmAction_Btn_Confirm {
            get {
                return ResourceManager.GetString("ConfirmAction_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CreatePrivateRoom_Btn_Cancel {
            get {
                return ResourceManager.GetString("CreatePrivateRoom_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Room.
        /// </summary>
        public static string CreatePrivateRoom_Btn_Create {
            get {
                return ResourceManager.GetString("CreatePrivateRoom_Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stones required to win:.
        /// </summary>
        public static string CreatePrivateRoom_Lbl_CaptureGoal {
            get {
                return ResourceManager.GetString("CreatePrivateRoom_Lbl_CaptureGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Private Room.
        /// </summary>
        public static string CreatePrivateRoom_Lbl_Title {
            get {
                return ResourceManager.GetString("CreatePrivateRoom_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string ForgotPassword_Btn_Accept {
            get {
                return ResourceManager.GetString("ForgotPassword_Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string ForgotPassword_Btn_Cancel {
            get {
                return ResourceManager.GetString("ForgotPassword_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or username cannot be empty..
        /// </summary>
        public static string ForgotPassword_Err_Empty {
            get {
                return ResourceManager.GetString("ForgotPassword_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or Username.
        /// </summary>
        public static string ForgotPassword_Lbl_EmailOrUsername {
            get {
                return ResourceManager.GetString("ForgotPassword_Lbl_EmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        public static string ForgotPassword_Lbl_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string ForgotVerification_Btn_Cancel {
            get {
                return ResourceManager.GetString("ForgotVerification_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string ForgotVerification_Btn_Confirm {
            get {
                return ResourceManager.GetString("ForgotVerification_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code cannot be empty..
        /// </summary>
        public static string ForgotVerification_Err_EmptyCode {
            get {
                return ResourceManager.GetString("ForgotVerification_Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent a 6-digit code to your email to change your password..
        /// </summary>
        public static string ForgotVerification_Lbl_Description {
            get {
                return ResourceManager.GetString("ForgotVerification_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation Required.
        /// </summary>
        public static string ForgotVerification_Lbl_Title {
            get {
                return ResourceManager.GetString("ForgotVerification_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string FriendList_Btn_Back {
            get {
                return ResourceManager.GetString("FriendList_Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string FriendList_Btn_Invite {
            get {
                return ResourceManager.GetString("FriendList_Btn_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string FriendList_Btn_Remove {
            get {
                return ResourceManager.GetString("FriendList_Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string FriendList_Lbl_Friend {
            get {
                return ResourceManager.GetString("FriendList_Lbl_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string FriendList_Lbl_Title {
            get {
                return ResourceManager.GetString("FriendList_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent..
        /// </summary>
        public static string FriendList_Msg_InvitationSent {
            get {
                return ResourceManager.GetString("FriendList_Msg_InvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This friend is offline..
        /// </summary>
        public static string FriendList_Msg_Offline {
            get {
                return ResourceManager.GetString("FriendList_Msg_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend removed..
        /// </summary>
        public static string FriendList_Msg_Removed {
            get {
                return ResourceManager.GetString("FriendList_Msg_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string FriendSearch_Btn_Add {
            get {
                return ResourceManager.GetString("FriendSearch_Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string FriendSearch_Btn_Back {
            get {
                return ResourceManager.GetString("FriendSearch_Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string FriendSearch_Btn_Search {
            get {
                return ResourceManager.GetString("FriendSearch_Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a username to search..
        /// </summary>
        public static string FriendSearch_Err_EmptySearch {
            get {
                return ResourceManager.GetString("FriendSearch_Err_EmptySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string FriendSearch_Lbl_Search {
            get {
                return ResourceManager.GetString("FriendSearch_Lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Friends.
        /// </summary>
        public static string FriendSearch_Lbl_Title {
            get {
                return ResourceManager.GetString("FriendSearch_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend request sent..
        /// </summary>
        public static string FriendSearch_Msg_RequestSent {
            get {
                return ResourceManager.GetString("FriendSearch_Msg_RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string GameBoard_Btn_Report {
            get {
                return ResourceManager.GetString("GameBoard_Btn_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surrender.
        /// </summary>
        public static string GameBoard_Btn_Surrender {
            get {
                return ResourceManager.GetString("GameBoard_Btn_Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The match has started..
        /// </summary>
        public static string GameBoard_Chat_GameStarted {
            get {
                return ResourceManager.GetString("GameBoard_Chat_GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good luck!.
        /// </summary>
        public static string GameBoard_Chat_GoodLuck {
            get {
                return ResourceManager.GetString("GameBoard_Chat_GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        public static string GameBoard_Lbl_Black {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat is not available for guests..
        /// </summary>
        public static string GameBoard_Lbl_ChatDisabledGuest {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_ChatDisabledGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match Chat.
        /// </summary>
        public static string GameBoard_Lbl_ChatTitle {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opponent.
        /// </summary>
        public static string GameBoard_Lbl_Opponent {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        public static string GameBoard_Lbl_System {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White.
        /// </summary>
        public static string GameBoard_Lbl_White {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU.
        /// </summary>
        public static string GameBoard_Lbl_You {
            get {
                return ResourceManager.GetString("GameBoard_Lbl_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opponent&apos;s turn! Waiting for move....
        /// </summary>
        public static string GameBoard_Status_OpponentTurn {
            get {
                return ResourceManager.GetString("GameBoard_Status_OpponentTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s your turn! Click on an intersection.
        /// </summary>
        public static string GameBoard_Status_YourTurn {
            get {
                return ResourceManager.GetString("GameBoard_Status_YourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surrender.
        /// </summary>
        public static string GameBoard_Surrender_Confirm {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to surrender this match?.
        /// </summary>
        public static string GameBoard_Surrender_Message {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surrender Match.
        /// </summary>
        public static string GameBoard_Surrender_Title {
            get {
                return ResourceManager.GetString("GameBoard_Surrender_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a message....
        /// </summary>
        public static string GameBoard_Txt_ChatPlaceholder {
            get {
                return ResourceManager.GetString("GameBoard_Txt_ChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string JoinPrivateRoom_Btn_Cancel {
            get {
                return ResourceManager.GetString("JoinPrivateRoom_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string JoinPrivateRoom_Btn_Join {
            get {
                return ResourceManager.GetString("JoinPrivateRoom_Btn_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a room code..
        /// </summary>
        public static string JoinPrivateRoom_Err_EmptyCode {
            get {
                return ResourceManager.GetString("JoinPrivateRoom_Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room code (e.g. XK92P).
        /// </summary>
        public static string JoinPrivateRoom_Lbl_Code {
            get {
                return ResourceManager.GetString("JoinPrivateRoom_Lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Private Room.
        /// </summary>
        public static string JoinPrivateRoom_Lbl_Title {
            get {
                return ResourceManager.GetString("JoinPrivateRoom_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Lang_Btn_Accept {
            get {
                return ResourceManager.GetString("Lang_Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Lang_Btn_Cancel {
            get {
                return ResourceManager.GetString("Lang_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Language.
        /// </summary>
        public static string Lang_Modal_Title {
            get {
                return ResourceManager.GetString("Lang_Modal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Login_Btn_Exit {
            get {
                return ResourceManager.GetString("Login_Btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as Guest.
        /// </summary>
        public static string Login_Btn_Guest {
            get {
                return ResourceManager.GetString("Login_Btn_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Login_Btn_LanguageLabel {
            get {
                return ResourceManager.GetString("Login_Btn_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string Login_Btn_Submit {
            get {
                return ResourceManager.GetString("Login_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is not allowed to sign in..
        /// </summary>
        public static string Login_Err_AccountRestricted {
            get {
                return ResourceManager.GetString("Login_Err_AccountRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password is incorrect..
        /// </summary>
        public static string Login_Err_IncorrectPassword {
            get {
                return ResourceManager.GetString("Login_Err_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your username or email and password..
        /// </summary>
        public static string Login_Err_Required {
            get {
                return ResourceManager.GetString("Login_Err_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign-in could not be completed. Check the server connection and try again..
        /// </summary>
        public static string Login_Err_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Login_Err_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No account was found for that username or email..
        /// </summary>
        public static string Login_Err_UserNotFound {
            get {
                return ResourceManager.GetString("Login_Err_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or email.
        /// </summary>
        public static string Login_Lbl_Email {
            get {
                return ResourceManager.GetString("Login_Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Login_Lbl_Password {
            get {
                return ResourceManager.GetString("Login_Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string Login_Lbl_Title {
            get {
                return ResourceManager.GetString("Login_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Login_Lnk_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_Lnk_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Don&apos;t have an account? Sign up.
        /// </summary>
        public static string Login_Lnk_Register {
            get {
                return ResourceManager.GetString("Login_Lnk_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign-in successful..
        /// </summary>
        public static string Login_Msg_Success {
            get {
                return ResourceManager.GetString("Login_Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        public static string Login_Tip_ChangeLanguage {
            get {
                return ResourceManager.GetString("Login_Tip_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user@mail.com.
        /// </summary>
        public static string Login_Txt_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_Txt_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .........
        /// </summary>
        public static string Login_Txt_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_Txt_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string NewPassword_Btn_Cancel {
            get {
                return ResourceManager.GetString("NewPassword_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Change.
        /// </summary>
        public static string NewPassword_Btn_ConfirmChange {
            get {
                return ResourceManager.GetString("NewPassword_Btn_ConfirmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords cannot be empty..
        /// </summary>
        public static string NewPassword_Err_Empty {
            get {
                return ResourceManager.GetString("NewPassword_Err_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match..
        /// </summary>
        public static string NewPassword_Err_Mismatch {
            get {
                return ResourceManager.GetString("NewPassword_Err_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string NewPassword_Lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string NewPassword_Lbl_NewPassword {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string NewPassword_Lbl_Title {
            get {
                return ResourceManager.GetString("NewPassword_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save and Close.
        /// </summary>
        public static string Options_Btn_SaveAndClose {
            get {
                return ResourceManager.GetString("Options_Btn_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atari Go Multiplayer v1.0.
        /// </summary>
        public static string Options_Lbl_AppVersion {
            get {
                return ResourceManager.GetString("Options_Lbl_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background Music.
        /// </summary>
        public static string Options_Lbl_BackgroundMusic {
            get {
                return ResourceManager.GetString("Options_Lbl_BackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language:.
        /// </summary>
        public static string Options_Lbl_Language {
            get {
                return ResourceManager.GetString("Options_Lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effects.
        /// </summary>
        public static string Options_Lbl_SoundEffects {
            get {
                return ResourceManager.GetString("Options_Lbl_SoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string Options_Lbl_Title {
            get {
                return ResourceManager.GetString("Options_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disband Room.
        /// </summary>
        public static string PrivateRoom_Btn_Disband {
            get {
                return ResourceManager.GetString("PrivateRoom_Btn_Disband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Friends.
        /// </summary>
        public static string PrivateRoom_Btn_InviteFriends {
            get {
                return ResourceManager.GetString("PrivateRoom_Btn_InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        public static string PrivateRoom_Btn_Leave {
            get {
                return ResourceManager.GetString("PrivateRoom_Btn_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simulate Opponent.
        /// </summary>
        public static string PrivateRoom_Btn_SimulateOpponent {
            get {
                return ResourceManager.GetString("PrivateRoom_Btn_SimulateOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active rules.
        /// </summary>
        public static string PrivateRoom_Lbl_ActiveRules {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_ActiveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a stones to capture.
        /// </summary>
        public static string PrivateRoom_Lbl_Captures {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_Captures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string PrivateRoom_Lbl_Host {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation code.
        /// </summary>
        public static string PrivateRoom_Lbl_InvitationCode {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_InvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Room.
        /// </summary>
        public static string PrivateRoom_Lbl_Title {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You (Guest).
        /// </summary>
        public static string PrivateRoom_Lbl_YouGuest {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_YouGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You (Host).
        /// </summary>
        public static string PrivateRoom_Lbl_YouHost {
            get {
                return ResourceManager.GetString("PrivateRoom_Lbl_YouHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ProfileCustomization_Btn_ChangePassword {
            get {
                return ResourceManager.GetString("ProfileCustomization_Btn_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string ProfileCustomization_Btn_Close {
            get {
                return ResourceManager.GetString("ProfileCustomization_Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string ProfileCustomization_Btn_Update {
            get {
                return ResourceManager.GetString("ProfileCustomization_Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string ProfileCustomization_Lbl_Email {
            get {
                return ResourceManager.GetString("ProfileCustomization_Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your Avatar.
        /// </summary>
        public static string ProfileCustomization_Lbl_SelectAvatar {
            get {
                return ResourceManager.GetString("ProfileCustomization_Lbl_SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customization.
        /// </summary>
        public static string ProfileCustomization_Lbl_Title {
            get {
                return ResourceManager.GetString("ProfileCustomization_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string ProfileCustomization_Lbl_Username {
            get {
                return ResourceManager.GetString("ProfileCustomization_Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile updated succesfully.
        /// </summary>
        public static string ProfileCustomization_Msg_Updated {
            get {
                return ResourceManager.GetString("ProfileCustomization_Msg_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Register_Btn_Back {
            get {
                return ResourceManager.GetString("Register_Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string Register_Btn_Register {
            get {
                return ResourceManager.GetString("Register_Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username and email cannot be empty..
        /// </summary>
        public static string Register_Err_EmptyFields {
            get {
                return ResourceManager.GetString("Register_Err_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Register_Lbl_Email {
            get {
                return ResourceManager.GetString("Register_Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password (Min. 8 chars, 1 Uppercase).
        /// </summary>
        public static string Register_Lbl_Password {
            get {
                return ResourceManager.GetString("Register_Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registration.
        /// </summary>
        public static string Register_Lbl_Title {
            get {
                return ResourceManager.GetString("Register_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Register_Lbl_Username {
            get {
                return ResourceManager.GetString("Register_Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Add new friend.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_AddFriend {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Private Room.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_CreatePrivateRoom {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_CreatePrivateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customize.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Customize {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email ✉.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Email {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Invite {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join with Code.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_JoinWithCode {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_JoinWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_Options {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play Multiplayer.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_PlayMultiplayer {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_PlayMultiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        public static string RegisterPlayerLobby_Btn_SignOut {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Btn_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 👥 Friends List.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_FriendsList {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_FriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🏆 Global Top.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_TopGlobal {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_TopGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins: .
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_Victories {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_Victories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAIN LOBBY - Welcome .
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_Welcome {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What would you
        ///      like to do?.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_WhatToDo {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_WinsHeader {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_WinsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Profile.
        /// </summary>
        public static string RegisterPlayerLobby_Lbl_YourProfile {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Lbl_YourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search friend....
        /// </summary>
        public static string RegisterPlayerLobby_Txt_SearchFriendPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPlayerLobby_Txt_SearchFriendPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string ReportPlayer_Btn_Cancel {
            get {
                return ResourceManager.GetString("ReportPlayer_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit Report.
        /// </summary>
        public static string ReportPlayer_Btn_Submit {
            get {
                return ResourceManager.GetString("ReportPlayer_Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Additional Details (Optional).
        /// </summary>
        public static string ReportPlayer_Lbl_Details {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player: .
        /// </summary>
        public static string ReportPlayer_Lbl_PlayerFormat {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_PlayerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Infraction Reason.
        /// </summary>
        public static string ReportPlayer_Lbl_Reason {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report Player.
        /// </summary>
        public static string ReportPlayer_Lbl_Title {
            get {
                return ResourceManager.GetString("ReportPlayer_Lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cheating or Hacking.
        /// </summary>
        public static string ReportPlayer_Reason_Cheating {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Cheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offensive Language.
        /// </summary>
        public static string ReportPlayer_Reason_OffensiveLanguage {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_OffensiveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string ReportPlayer_Reason_Other {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsportsmanlike Conduct.
        /// </summary>
        public static string ReportPlayer_Reason_Unsportsmanlike {
            get {
                return ResourceManager.GetString("ReportPlayer_Reason_Unsportsmanlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string SearchingOpponent_Btn_Cancel {
            get {
                return ResourceManager.GetString("SearchingOpponent_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simulate match found.
        /// </summary>
        public static string SearchingOpponent_Btn_SimulateMatch {
            get {
                return ResourceManager.GetString("SearchingOpponent_Btn_SimulateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching....
        /// </summary>
        public static string SearchingOpponent_Lbl_Searching {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEARCHING FOR OPPONENT.
        /// </summary>
        public static string SearchingOpponent_Lbl_SearchingOpponent {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_SearchingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string SearchingOpponent_Lbl_You {
            get {
                return ResourceManager.GetString("SearchingOpponent_Lbl_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Verification_Btn_Cancel {
            get {
                return ResourceManager.GetString("Verification_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm and Enter.
        /// </summary>
        public static string Verification_Btn_Confirm {
            get {
                return ResourceManager.GetString("Verification_Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code cannot be empty..
        /// </summary>
        public static string Verification_Err_EmptyCode {
            get {
                return ResourceManager.GetString("Verification_Err_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have sent a 6-digit code to your email to verify your account..
        /// </summary>
        public static string Verification_Lbl_Description {
            get {
                return ResourceManager.GetString("Verification_Lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation Required.
        /// </summary>
        public static string Verification_Lbl_Title {
            get {
                return ResourceManager.GetString("Verification_Lbl_Title", resourceCulture);
            }
        }
    }
}
