syntax = "proto3";

option csharp_namespace = "AtariGo.Contracts";

package atarigo.authentication.v1;

service Authentication {
  rpc Login (LoginRequest) returns (LoginResponse);
}

message LoginRequest {
  string identifier = 1;
  string password = 2;
}

message LoginResponse {
  LoginResult result = 1;
  int32 user_id = 2;
  string user_name = 3;
  string session_token = 4;
}

enum LoginResult {
  LOGIN_RESULT_UNSPECIFIED = 0;
  LOGIN_RESULT_SUCCESS = 1;
  LOGIN_RESULT_USER_NOT_FOUND = 2;
  LOGIN_RESULT_INCORRECT_PASSWORD = 3;
  LOGIN_RESULT_ACCOUNT_RESTRICTED = 4;
}
